# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_is_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('name', 'id'), 'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
        migrations.AlterField(
            model_name='question',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u0432 \u0430\u0440\u0445\u0438\u0432\u0435'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0432\u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='tags.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
